version: "3.8"

services:
  telegraf:
    image: telegraf:1.37
    container_name: telegraf-system
    privileged: true
    restart: unless-stopped
    environment:
      - INFLUX_TOKEN=<SYSTEM_TOKEN>
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_MOUNT_PREFIX=/host
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro
    networks:
      - monitoring

networks:
  monitoring:
    external: true

